all: factors factorTest floatLoop increment intdiv loopmod overflow taninf

factors: factors.c
	gcc -o factors factors.c

factorTest: factorTest.c
	gcc -o factorTest factorTest.c

floatLoop: floatLoop.c
	gcc -o floatLoop floatLoop.c

increment: increment.c
	gcc -o increment increment.c

intdiv: intdiv.c
	gcc -o intdiv intdiv.c

loopmod: loopmod.c
	gcc -o loopmod loopmod.c

overflow: overflow.c
	gcc -o overflow overflow.c

taninf: taninf.c
	gcc -o taninf taninf.c -lm

clean: 
	rm factors factorTest floatLoop increment intdiv loopmod overflow taninf
