#!/bin/bash
while [ true ]
do
	TOPPROCESS=$(ps -eo pid -eo pcpu -eo time -eo command | sort -k 3 -r | grep a.out | head -n 1)
	PID=$(echo $TOPPROCESS | cut -f 1 -d " ")
	TIME=$(echo $TOPPROCESS | cut -f 3 -d " ")
	SEC=$(echo $TIME | cut -d : -f 3)
	MIN=$(echo $TIME | cut -d : -f 2)
	HOUR=$(echo $TIME | cut -d : -f 1)
	# 10#'s force base 10 interpretation
	TIME=$(( 10#$SEC+60*10#$MIN+3600*10#$HOUR ))
	if (( TIME > 20 )) ; then
		#echo $TOPPROCESS
		echo killing $TOPPROCESS
		kill -9 $PID
	fi
	sleep 1
done
